#!/usr/bin/env bash

if [[ "$(docker images -q ubuntu-builder 2> /dev/null)" == "" ]]; then
	docker build -t ubuntu-builder .
fi

docker run -u $(id -u):$(id -g) -w /build -it -v$(pwd):/build --rm ubuntu-builder make "$@"

exit $?
